---
- hosts: "{{ host }}"
  remote_user: root
  become: yes
  gather_facts: no
  vars:
    user: "{{ user }}"
  tasks:
   - name: send an email
     local_action: mail
       host=
       port=
       username=
       password=
       from=
       to=
       subject=
       body=
